### ISSUE TITLE
Issue with LHE weights

### ISSUE THREAD

**Issue by bryates** [TopEFT/topcoffea#144]
Some of our LHE weights (including renormalization/factorization and PDF) have empty events. For now, I'm filling these with 1, but we need to understand why this is happening.

**Comment by kmohrman** [comment]
This issue was resolved a couple weeks ago via the following test: We set the weights to 0 instead of 1, and this resulted in very small changes to the limits (changes usually within a percent, but in some cases as large as 2%, but this could also be due to other factors e.g. fluctuations and issues with interpolation since I was only scanning 25 points). This test was run with only signal samples, and for shape uncertainties only included the `renormfact` uncertainty (though rate uncertainties were also included).

We expected the issue to have only a small impact, since from @Andrew42's checks of the lobster logs, we knew this issue was only affecting a small fraction (~3%) of a subset of our signal samples. So these results seem consistent with our expectations. 

From this, we concluded that our current handling of the issue (i.e. setting the missing weights to 1) is sufficient.
