### ISSUE TITLE
Systematics with NaN

### ISSUE THREAD

**Issue by bryates** [TopEFT/topcoffea#163]
It looks like the `PreFire` systematics contain some `NaN` values, causing issues with the datacard maker:

```python
('PreFiringUp',) [ 0.00000000e+00  0.00000000e+00  7.05479544e-03  5.56694072e-02
  1.66547486e+05  1.39621340e+34  1.45597271e+16             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
  7.17334946e+31             nan             nan             nan
             nan  2.38377475e+29             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
  4.08705212e+32             nan  4.11227915e+16  4.65035655e+30
             nan             nan             nan  4.00895028e+24
...
```
For now we can try `np.nan_to_num()`, but we should figure out why. @andrea21z could this be related to the `nanoAODv8` vs `v9` differences?

**Comment by andrea21z** [comment]
This is very strange, I have run with several samples for 2016, 2017 and 2018 with nanoAODv9 printing `events.L1PreFiringWeight.Up` and I don't see NaNs... And if you run with nanoAODv8 you will get an error because PreFiring branch does not exist, so I am not sure what is happening...

With which sample/year is this happening to you?

**Comment by bryates** [comment]
> This is very strange, I have run with several samples for 2016, 2017 and 2018 with nanoAODv9 printing `events.L1PreFiringWeight.Up` and I don't see NaNs... And if you run with nanoAODv8 you will get an error because PreFiring branch does not exist, so I am not sure what is happening...
> 
> With which sample/year is this happening to you?

@kmohrman can you list the samples you ran to create `jan28_UL18SigBkgNoZZ_njets-bl0pt_withSys.pkl.gz`?

**Comment by kmohrman** [comment]
As mentioned in PR #179, it turns out this issue was caused by the `add()` method of [`coffea.analysis_tools.Weights`](https://coffeateam.github.io/coffea/api/coffea.analysis_tools.Weights.html) modifying the up/down weights we pass to it. Our solution was to pass copies of the variables to `add()` (rather than the variables themselves).
