### ISSUE TITLE
Gen weights for future skimming

### ISSUE THREAD

**Issue by bryates** [TopEFT/topcoffea#38]
This is just a reminder that when we eventually produce skimmed versions of our nanoAOD files, we need to ensure `genWeight` stores the **unskimmed** values. It seems to only be used for non-EFT MC samples, as the data and EFT samples just use 1:
https://github.com/TopEFT/topcoffea/blob/2df1290ca69d242255e05ab9dfe4a696f31754a1/analysis/topEFT/topeft.py#L420

**Comment by bryates** [comment]
I've assigned this to the people likely to work on skimmed files in the future.

**Comment by kmohrman** [comment]
Just wanted to link this issue to the relevant PR #122. The approach taken was not to store the sum of the weights in the NAOD, but rather to store the value in the JSONs produced when making the skims. This should allow us to access the complete and correct sum of weights variables when using the skimmed samples.

The next step is to propagate this into the code, so that scale by the sum fo the weights in the processor. This will make the current, ad hoc normalization methods for EFT samples (evaluating the sum fo the weights histogram in all of the scripts that come after the processor, e.g. plotters, yield tools scripts, data card maker, etc.) unnecessary.

**Comment by kmohrman** [comment]
This issue has been addressed (primarily by PR #122, PR #151, and PR #194).
