### ISSUE TITLE
Genrun.py uses old-style config files

### ISSUE THREAD

**Issue by klannon** [TopEFT/topcoffea#39]
It should be updated to use the new json file approach that run.py uses.

**Comment by kmohrman** [comment]
@jlawrenc, just wondering about the status of this issue? Looks like the Genrun.py is still using the old configs (from before we moved to the JSON file approach). However, I'm not sure if it's worth spending time on this right now. Should we leave the issue open for now if you intend to update the script at some point, or otherwise should we just close it?

**Comment by jlawrenc** [comment]
@kmohrman according to my notes, we decided updating this was not worth the work investment, since there was not a need for this. I think we can close to issue, unless this is wanted for a reason I am not aware of.

**Comment by kmohrman** [comment]
Sounds good, I'll close it now as you suggest.
